// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uqpjgxkbevfrlatbclgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxcGpneGtiZXZmcmxhdGJjbGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTU0NzQsImV4cCI6MjA2OTE3MTQ3NH0.lZzig26w3PF5igKAQlBxF_sxXUHccoTJtXlyRZG8uwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);